# This is a basic workflow to help you get started with Actions

name: Github Action Maven Build Example
on:
  push:
    branches: [ master ]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name:  Step 1 checkout main branch from github
        uses: actions/checkout@v1

      # Runs a single command using the runners shell
      - name: Step 2 setup jdk 14
        uses: actions/setup-java@v1
        with:
            java-version: 14
      - name: step 3 have maven project build maven project
        run: mvn clean test
   
      # Runs a set of commands using the runners shell
      - name: run
        run: mvn clean compile exec:java  
